# Generated by Django 5.0.1 on 2024-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_drink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
