# Generated by Django 5.0.1 on 2024-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveuser',
            old_name='gender',
            new_name='transaction_origin',
        ),
        migrations.RenameField(
            model_name='receiveuser',
            old_name='marrital_status',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='senduser',
            old_name='gender',
            new_name='transaction_origin',
        ),
        migrations.RenameField(
            model_name='senduser',
            old_name='marrital_status',
            new_name='transaction_type',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marrital_status',
            field=models.CharField(choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40),
        ),
    ]
