# Generated by Django 5.0.1 on 2024-02-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_receiveuser_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiveuser',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='senduser',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='receiveuser',
            name='transaction_origin',
        ),
        migrations.RemoveField(
            model_name='receiveuser',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='transaction_origin',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='fax',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drives Licence'), ('international_passport', 'International Passport')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='marrital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AddField(
            model_name='receiveuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='senduser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='fax',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AddField(
            model_name='senduser',
            name='identity_type',
            field=models.CharField(blank=True, choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drives Licence'), ('international_passport', 'International Passport')], max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='marrital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('single', 'Single'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AddField(
            model_name='senduser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receiveuser',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='receiveuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='mobile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
