# Generated by Django 5.0.1 on 2024-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_receiveuser_options_alter_senduser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senduser',
            options={'ordering': ['-transaction_type']},
        ),
        migrations.RenameField(
            model_name='senduser',
            old_name='fax',
            new_name='account_number',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='marrital_status',
        ),
        migrations.RemoveField(
            model_name='senduser',
            name='state',
        ),
        migrations.AddField(
            model_name='senduser',
            name='transaction_origin',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash Deposit', 'Cash Deposit'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='senduser',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Wallet', 'Wallet'), ('Memo Name', 'Memo Name'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='receiveuser',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='receive'),
        ),
        migrations.AlterField(
            model_name='receiveuser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='receive'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='sent'),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='sent'),
        ),
    ]
