# Generated by Django 5.0.1 on 2024-02-16 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_receiveuser_options_alter_senduser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveuser',
            name='transaction_origin',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Wallet', 'Wallet'), ('Momo Name', 'Momo Name'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='receiveuser',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash Deposit', 'Cash Deposit'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='transaction_origin',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Wallet', 'Wallet'), ('Momo Name', 'Momo Name'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='senduser',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash Deposit', 'Cash Deposit'), ('Mobile Money', 'Mobile Money'), ('Other', 'Other')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='CURRENCY_CONVERTOR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency_from', models.CharField(blank=True, choices=[('European Euro', 'European Euro'), ('British pound', 'British pound'), ('United States dollar', 'United States dollar')], max_length=40, null=True)),
                ('currency_to', models.CharField(blank=True, choices=[('European Euro', 'European Euro'), ('British pound', 'British pound'), ('United States dollar', 'United States dollar')], max_length=40, null=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-full_name'],
            },
        ),
    ]
