# Generated by Django 5.0.1 on 2024-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('base_code', models.CharField(max_length=50)),
                ('EUR', models.CharField(max_length=200)),
                ('GBP', models.CharField(max_length=200)),
                ('USD', models.CharField(max_length=200)),
            ],
        ),
    ]
